### ISSUE TITLE
Fix integration tests for Exasol v8

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-driver-lua#91] opened 2024-04-23 14:22 UTC
Integration tests using Exasol 8.18.1 currently fail with the following error messages (see [detailed log](https://github.com/exasol/exasol-driver-lua/actions/runs/8801975507/job/24156615539?pr=90)):
```
291 successes / 5 failures / 10 errors / 0 pending : 48.849688 seconds

Failure -> spec/integration/Connection_spec.lua @ 150
Connection commit() returns true for empty transaction
spec/integration/Connection_spec.lua:54: setautocommit result
Expected objects to be the same.
Passed in:
(boolean) false
Expected:
(boolean) true

stack traceback:
	spec/integration/Connection_spec.lua:54: in upvalue 'set_autocommit'
	spec/integration/Connection_spec.lua:151: in function <spec/integration/Connection_spec.lua:150>


Failure -> spec/integration/Connection_spec.lua @ 252
Connection close() does not close cursors
spec/integration/Connection_spec.lua:253: E-EDL-6: Error executing statement 'select 1': E-EDL-18: Timeout after 5.000016s and 79589 tries waiting for data,  last result: false, last error: 0

stack traceback:
	spec/integration/Connection_spec.lua:253: in function <spec/integration/Connection_spec.lua:252>


Failure -> spec/integration/Environment_spec.lua @ 73
Environment does not close a connection when closing an environment
spec/integration/Environment_spec.lua:78: Expected objects to not be the same.
Passed in:
(nil)
Did not expect:
type nil

stack traceback:
	spec/integration/Environment_spec.lua:78: in function <spec/integration/Environment_spec.lua:73>


Failure -> spec/integration/Websocket_spec.lua @ 100
Websocket with tls_protocol option fails for invalid value "invalid"
spec/integration/Websocket_spec.lua:40: Expected a different error.
Caught:
(string) 'E-EDL-1: Error connecting to 'wss://172.18.0.2:8563': 'Connection to 172.18.0.2:8563 failed: connection refused''
Expected:
(string) 'E-EDL-1: Error connecting to 'wss://172.18.0.2:8563': 'Failed to create SSL socket: 'invalid protocol (invalid)'''

stack traceback:
	spec/integration/Websocket_spec.lua:40: in upvalue 'assert_connect_fails'
	spec/integration/Websocket_spec.lua:101: in function <spec/integration/Websocket_spec.lua:100>
./src/luasql/exasol/Websocket.lua:52: E-EDL-1: Error connecting to 'wss://172.18.0.2:8563': 'Connection to 172.18.0.2:8563 failed: connection refused'

stack traceback:
	/home/runner/.luarocks/share/lua/5.4/ExaError.lua:142: in function 'ExaError.raise'
	./src/luasql/exasol/Websocket.lua:52: in function <./src/luasql/exasol/Websocket.lua:43>
	(...tail calls...)
	spec/integration/Websocket_spec.lua:24: in upvalue 'connect'
	spec/integration/Websocket_spec.lua:32: in upvalue 'assert_connect_successful'
	spec/integration/Websocket_spec.lua:114: in function <spec/integration/Websocket_spec.lua:113>


Error -> spec/integration/Websocket_spec.lua @ 113
Websocket with tls_options connects successfully for value "no_tlsv1_3"
./src/luasql/exasol/Websocket.lua:52: E-EDL-1: Error connecting to 'wss://172.18.0.2:8563': 'Connection to 172.18.0.2:8563 failed: connection refused'

stack traceback:
	/home/runner/.luarocks/share/lua/5.4/ExaError.lua:142: in function 'ExaError.raise'
	./src/luasql/exasol/Websocket.lua:52: in function <./src/luasql/exasol/Websocket.lua:43>
	(...tail calls...)
	spec/integration/Websocket_spec.lua:24: in upvalue 'connect'
	spec/integration/Websocket_spec.lua:32: in upvalue 'assert_connect_successful'
	spec/integration/Websocket_spec.lua:114: in function <spec/integration/Websocket_spec.lua:113>


Error -> spec/integration/Websocket_spec.lua @ 113
Websocket with tls_options connects successfully for value "no_tlsv1"
./src/luasql/exasol/Websocket.lua:52: E-EDL-1: Error connecting to 'wss://172.18.0.2:8563': 'Connection to 172.18.0.2:8563 failed: connection refused'

stack traceback:
	/home/runner/.luarocks/share/lua/5.4/ExaError.lua:142: in function 'ExaError.raise'
	./src/luasql/exasol/Websocket.lua:52: in function <./src/luasql/exasol/Websocket.lua:43>
	(...tail calls...)
	spec/integration/Websocket_spec.lua:24: in upvalue 'connect'
	spec/integration/Websocket_spec.lua:32: in upvalue 'assert_connect_successful'
	spec/integration/Websocket_spec.lua:114: in function <spec/integration/Websocket_spec.lua:113>


Error -> spec/integration/luasql_compatibility_spec.lua @ 99
LuaSQL compatibility with driver exasol Connection Cursor before_each
spec/integration/luasql_compatibility_spec.lua:100: E-EDL-6: Error executing statement 'select 1 as "ID", 'foobar' as "NAME"': E-EDL-4: Error receiving data while waiting for response for 4.996574s: 'message timeout'

stack traceback:
	spec/integration/luasql_compatibility_spec.lua:100: in function <spec/integration/luasql_compatibility_spec.lua:99>


Error -> spec/integration/luasql_compatibility_spec.lua @ 103
LuaSQL compatibility with driver exasol Connection Cursor after_each
spec/integration/luasql_compatibility_spec.lua:104: attempt to index a nil value (upvalue 'cur')

stack traceback:
	spec/integration/luasql_compatibility_spec.lua:104: in function <spec/integration/luasql_compatibility_spec.lua:103>


Error: test suite failed.
```

**Comment by redcatbear** [comment] 2024-07-01 07:50
Problem still persists with 8.26.0 and 8.27.0.

**Comment by redcatbear** [comment] 2024-07-17 09:09
Duplicate of #56.

**Closed by redcatbear** 2024-07-17 09:09 UTC
Labels: duplicate
